apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: argo-app-prject
  namespace: argo
spec:
  project: default
  source:
    repoURL: https://github.com/lucasrestrepo/argocd-templates.git
    targetRevision: HEAD
    path: /
  destination:
    server: 'https://kubernetes.default.svc'  