apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nodered
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-org/my-git-repo'
    targetRevision: main
    path: nodered
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
