apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-app-deployment
  namespace: argo
spec:
  selector:
    matchLabels:
      app: argo-app
  template:
    metadata:
      labels:
        app: argo-app
    spec:
      containers:
      - name: argo-app
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080