apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodered
  namespace: default
  labels:
    app: nodered
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodered
  template:
    metadata:
      labels:
        app: nodered
    spec:
      containers:
        - name: nodered
          image: nodered/node-red:latest
          ports:
            - containerPort: 1880
              protocol: TCP
          volumeMounts:
            - name: nodered-storage
              mountPath: /data
      volumes:
        - name: nodered-storage
          persistentVolumeClaim:
            claimName: nodered-pvc
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
